# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_topic_distrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.CharField(blank=True, max_length=22, null=True)),
                ('t0', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t1', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t2', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t3', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t4', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t5', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t6', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t7', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t8', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t9', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t10', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t11', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t12', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t13', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t14', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t15', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t16', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t17', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t18', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t19', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t20', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t21', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t22', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t23', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t24', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t25', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t26', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t27', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t28', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t29', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t30', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t31', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t32', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t33', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t34', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t35', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t36', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t37', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t38', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t39', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t40', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t41', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t42', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t43', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t44', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t45', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t46', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t47', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t48', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('t49', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(unique=True)),
                ('words', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
