# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class doc_topic_distrib(models.Model):
	doc_id = models.IntegerField()
	title = models.CharField(max_length=500, blank=True, null=True)
	datetime = models.CharField(max_length=22, blank=True, null=True)
	t0 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t1 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t2 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t3 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t4 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t5 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t6 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t7 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t8 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t9 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t10 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t11 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t12 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t13 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t14 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t15 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t16 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t17 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t18 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t19 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t20 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t21 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t22 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t23 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t24 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t25 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t26 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t27 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t28 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t29 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t30 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t31 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t32 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t33 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t34 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t35 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t36 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t37 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t38 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t39 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t40 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t41 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t42 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t43 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t44 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t45 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t46 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t47 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t48 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)
	t49 = models.DecimalField(max_digits=5, decimal_places=4, default=0.0)

class topics(models.Model):
	topic_id = models.IntegerField(unique=True)
	words = models.CharField(max_length=500, blank=True, null=True)